title: Cognitive Analytics Developer
author: Jaspreet Singh
description: > # this means to ignore newlines until "baseurl:"
  I write about software and AI
#theme: minima
# social links
twitter_username: jaspreet_dev
linkedin_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman