title: Jaspreet Singh
author: Jaspreet Singh
description: > # this means to ignore newlines until "baseurl:"
 
theme: minima
# social links
twitter_username: jaspreet_dev
linkedin_username: iamjaspreet

show_excerpts: true # set to false to remove excerpts on the homepage

